# Generated by Django 5.2.10 on 2026-01-08 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CandidateSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique session identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Session creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Session completion timestamp", null=True
                    ),
                ),
                (
                    "current_phase",
                    models.CharField(
                        choices=[
                            ("onboarding", "Onboarding"),
                            ("information_gathering", "Information Gathering"),
                            ("technical_screening", "Technical Screening"),
                            ("closing", "Closing"),
                        ],
                        default="onboarding",
                        help_text="Current interview phase",
                        max_length=50,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Candidate's full name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Candidate's email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Candidate's phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Candidate's location",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "years_experience",
                    models.IntegerField(
                        blank=True,
                        help_text="Years of professional experience",
                        null=True,
                    ),
                ),
                (
                    "tech_stack",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of technologies the candidate knows",
                    ),
                ),
                (
                    "position_applied",
                    models.CharField(
                        blank=True,
                        help_text="Position the candidate is applying for",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid-Level"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("architect", "Architect"),
                        ],
                        help_text="Derived experience level based on years",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "generated_questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="AI-generated technical questions for this candidate",
                    ),
                ),
                (
                    "technical_responses",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Candidate's responses to technical questions",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the session is currently active",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the candidate (for security audit)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser user agent", null=True
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Overall sentiment score (-1 to 1)",
                        null=True,
                    ),
                ),
                (
                    "needs_intervention",
                    models.BooleanField(
                        default=False,
                        help_text="Flag if candidate seems frustrated/confused",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Session",
                "verbose_name_plural": "Candidate Sessions",
                "db_table": "candidate_sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="candidate_s_created_eb83a7_idx"
                    ),
                    models.Index(fields=["email"], name="candidate_s_email_224f4b_idx"),
                    models.Index(
                        fields=["current_phase"], name="candidate_s_current_1ee74e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="candidate_s_is_acti_4cc6c0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("assistant", "Assistant"),
                            ("user", "User"),
                            ("system", "System"),
                        ],
                        help_text="Who sent this message",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the message was sent"
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        blank=True,
                        help_text="Tokens consumed by this message (for cost tracking)",
                        null=True,
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Sentiment score for this message (-1 to 1)",
                        null=True,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        help_text="LLM model used for generation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="LLM response time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data extracted from user message",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Associated interview session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="talent_scout.candidatesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "timestamp"],
                        name="chat_messag_session_4a3fea_idx",
                    ),
                    models.Index(fields=["role"], name="chat_messag_role_ddd811_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TechnicalQuestion",
            fields=[
                (
                    "question_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField(help_text="The technical question")),
                (
                    "tech_stack",
                    models.JSONField(
                        default=list, help_text="Technologies this question targets"
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        help_text="Target experience level", max_length=50
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("expert", "Expert"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True, help_text="Question quality score (0-1)", null=True
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Session this question was generated for",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="talent_scout.candidatesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical Question",
                "verbose_name_plural": "Technical Questions",
                "db_table": "technical_questions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["experience_level"],
                        name="technical_q_experie_027ab6_idx",
                    ),
                    models.Index(
                        fields=["difficulty_level"],
                        name="technical_q_difficu_049db1_idx",
                    ),
                ],
            },
        ),
    ]
