# Generated by Django 5.2.10 on 2026-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent_scout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatesession",
            name="mcq_answers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Candidate's MCQ answers and evaluation results",
            ),
        ),
        migrations.AddField(
            model_name="candidatesession",
            name="mcq_questions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Generated MCQ questions per skill (5 per skill)",
            ),
        ),
        migrations.AddField(
            model_name="candidatesession",
            name="objective_evaluations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="LLM evaluations of objective question answers",
            ),
        ),
        migrations.AddField(
            model_name="candidatesession",
            name="objective_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Generated objective (open-ended) questions (3 total)",
            ),
        ),
        migrations.AddField(
            model_name="candidatesession",
            name="skill_ratings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="5-star ratings for each skill based on MCQ and objective performance",
            ),
        ),
    ]
